### ISSUE TITLE
Question how to use this package

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [tentone/aruco#1]
I have catkin_make and calibrate my usb_cam.
What is the commands to be executed to use this package?
Terminal 1: roscore
Terminal 3: roslaunch usb_cam usb_cam-test.launch
Terminal 3: roslaunch apriltags2_ros continuous_detection.launch 

what is the other commands? This package can see the x,y,z coordinates of a aruco marker, right?

**Comment by tentone** [comment]
Hi

To run this package and register lets tsay the marker 768 with size 15.6cm in the position 0,0,0 and rotaiton 0,0,0 use the following command 

rosrun aruco aruco _topic_camera:=\"camera topic" _topic_camera_info:=\"camera info topic" _marker768:="0.156_0_0_0_0_0_0"

**Comment by iou84** [comment]
Hallo there :)

Can I ask help for two things:
1) Is it possible to somehow put to a file the position of known markers and read from there?? 
(and how to read the?)
2) How can I get camera location from the aruco locations???

Thanks!!

**Comment by tentone** [comment]
Hi

You can introduce your launch parameters into a yaml file http://library.isr.ist.utl.pt/docs/roswiki/rosparam.html.

The camera location should be published in the topic_position that defaults to "aruco\position"

I hope this helps. Thanks

**Comment by iou84** [comment]
Thanks a lot for the quick & helpful response
I will try it tonight ????
________________________________
