### ISSUE TITLE
How to know the reference for multiple markers

### ISSUE THREAD

**Issue by akashcastelino** [tentone/aruco#5]
Hello,

I am using a marker board, in which the axis is drawn for each marker. 

When multiple markers are detected, how do I know the reference from which the camera pose is estimated?

Thanks in advance !

**Comment by tentone** [comment]
Hi

The camera pose is estimated from all the markers available.

More markers give you better camera pose values, but make sure that the size, position and rotation of all markers is good otherwise it will give wrong camera pose.

Cumps
